# Generated by Django 4.0 on 2021-12-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('number', models.TextField(null=True)),
                ('birthday', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('education1_name', models.TextField(null=True)),
                ('education1_degreeCourse', models.TextField(null=True)),
                ('education1_term', models.TextField(null=True)),
                ('education1_major', models.TextField(null=True)),
                ('education1_graduate', models.TextField(null=True)),
                ('education2_name', models.TextField(null=True)),
                ('education2_degreeCourse', models.TextField(null=True)),
                ('education2_term', models.TextField(null=True)),
                ('education2_major', models.TextField(null=True)),
                ('education2_graduate', models.TextField(null=True)),
                ('education3_name', models.TextField(null=True)),
                ('education3_degreeCourse', models.TextField(null=True)),
                ('education3_term', models.TextField(null=True)),
                ('education3_major', models.TextField(null=True)),
                ('education3_graduate', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
